name: Clarify
options:
  bundleIdPrefix: com.example.Clarify
packages:
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: "2.6.1"
targets:
  Clarify:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Clarify/Clarify
        createIntermediateGroups: true
    dependencies:
      - package: SwiftSoup
    settings:
      base:
        DEVELOPMENT_TEAM: YOUR_TEAM_ID # Replace with your Apple Developer Team ID
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
