import SwiftUI

struct AISummaryView: View {
    let title: String
    let summary: String
    let onDismiss: () -> Void
    @Environment(\.colorScheme) var colorScheme
    
    var body: some View {
        NavigationView {
            VStack(alignment: .leading, spacing: 20) {
                // Header
                VStack(alignment: .leading, spacing: 8) {
                    HStack {
                        Image(systemName: "brain.head.profile")
                            .font(.system(size: 20, weight: .medium))
                            .foregroundColor(.blue)
                        
                        Text("AI Summary")
                            .font(.system(size: 24, weight: .bold))
                            .foregroundColor(.primary)
                        
                        Spacer()
                        
                        Button("Done") {
                            onDismiss()
                        }
                        .font(.system(size: 16, weight: .medium))
                        .foregroundColor(.blue)
                    }
                    
                    Text(title)
                        .font(.system(size: 18, weight: .semibold))
                        .foregroundColor(.secondary)
                        .lineLimit(2)
                }
                
                Divider()
                
                // Summary Content
                ScrollView {
                    VStack(alignment: .leading, spacing: 16) {
                        Text(summary)
                            .font(.system(size: 17, weight: .regular, design: .serif))
                            .lineSpacing(6)
                            .foregroundColor(.primary)
                        
                        Spacer(minLength: 20)
                        
                        // Footer
                        HStack {
                            Image(systemName: "sparkles")
                                .font(.system(size: 14))
                                .foregroundColor(.secondary)
                            
                            Text("Generated by AI")
                                .font(.system(size: 14, weight: .medium))
                                .foregroundColor(.secondary)
                            
                            Spacer()
                        }
                        .padding(.top, 20)
                    }
                }
                
                Spacer()
            }
            .padding(.horizontal, 26)
            .padding(.vertical, 20)
            .background(Color(.systemBackground))
        }
    }
}

#Preview {
    AISummaryView(
        title: "Sample Article Title",
        summary: "This is a sample AI-generated summary of the article content. It provides a concise overview of the key points discussed in the article.",
        onDismiss: {}
    )
}
